ilanguage: python
python:
  - "2.7"
## command to install dependencies.
## not needed.https://packaging.python.org/en/latest/requirements/
#install: "pip install -r requirements.txt"
# # command to run tests
script: nosetests

