
FROM python:2.7-slim

ENV PYTHONUNBUFFERED 1

RUN mkdir /src
WORKDIR /src
RUN pip install --upgrade pip

# Start Template generated
{% for req in pip_requirements %}
RUN pip install --upgrade {{ req }}{% endfor%}
# End Template generated
